### ISSUE TITLE
exception during autocomplete for virtual field not defined in DB

### ISSUE THREAD

**Issue by beav** [wvanbergen/scoped_search#181]
We have a model obj with an `evr` field that's a composite of epoch + version + release. This is a virtual field that doesn't have a DB column, and is defined like this:

```ruby
scoped_search :on => :evr, :ext_method => :scoped_search_evr
```

If auto-complete tries to complete on this field, it will raise a stack trace:

```
ActiveModel::UnknownAttributeError: unknown attribute 'evr' for Class.
/opt/theforeman/tfm/root/usr/share/gems/gems/scoped_search-4.1.3/lib/scoped_search/definition.rb:116:in `column'
/opt/theforeman/tfm/root/usr/share/gems/gems/scoped_search-4.1.3/lib/scoped_search/definition.rb:123:in `type'
/opt/theforeman/tfm/root/usr/share/gems/gems/scoped_search-4.1.3/lib/scoped_search/definition.rb:144:in `numerical?'
/opt/theforeman/tfm/root/usr/share/gems/gems/scoped_search-4.1.3/lib/scoped_search/definition.rb:236:in `operator_by_field_name'
/opt/theforeman/tfm/root/usr/share/gems/gems/scoped_search-4.1.3/lib/scoped_search/auto_complete_builder.rb:273:in `complete_operator'
/opt/theforeman/tfm/root/usr/share/gems/gems/scoped_search-4.1.3/lib/scoped_search/auto_complete_builder.rb:47:in `build_autocomplete_options'
/opt/theforeman/tfm/root/usr/share/gems/gems/scoped_search-4.1.3/lib/scoped_search/auto_complete_builder.rb:21:in `auto_complete'
/opt/theforeman/tfm/root/usr/share/gems/gems/scoped_search-4.1.3/lib/scoped_search/definition.rb:319:in `complete_for'
/opt/theforeman/tfm-ror51/root/usr/share/gems/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:66:in `block in complete_for'
/opt/theforeman/tfm-ror51/root/usr/share/gems/gems/activerecord-5.1.6/lib/active_record/relation.rb:336:in `scoping'
/opt/theforeman/tfm-ror51/root/usr/share/gems/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:66:in `complete_for'
```

We enabled `:only_explicit => true` which reduces the likelihood of this error, but it would be good if there was way to disable auto-complete for this field.

scoped_search version: 4.1.3
AR version: 5.1.6

**Comment by PaulSD** [comment]
Is this fixed by https://github.com/wvanbergen/scoped_search/pull/178 (https://github.com/wvanbergen/scoped_search/commit/5fbb24280a34f85058bc829c82800f308a7132ef)?  https://github.com/wvanbergen/scoped_search/pull/172 seems to suggest that #178 might have fixed this...

@ares Any chance you could release a new version with https://github.com/wvanbergen/scoped_search/commit/5fbb24280a34f85058bc829c82800f308a7132ef ?

**Comment by ares** [comment]
Yup, I'll get to it next week I think

**Comment by beav** [comment]
thanks @PaulSD @ares !

**Comment by ares** [comment]
4.1.4 containing the fix has been pushed to rubygems.org

**Comment by beav** [comment]
It looks like this still happens with 4.1.4:

```
12:10:12 rails.1   | 2018-09-06T12:10:12 [E|app|1a047] ActiveModel::UnknownAttributeError: unknown attribute 'evr' for Class.
12:10:12 rails.1   |  | /home/vagrant/.rvm/gems/ruby-2.4.4/gems/scoped_search-4.1.4/lib/scoped_search/definition.rb:116:in `column'
12:10:12 rails.1   |  | /home/vagrant/.rvm/gems/ruby-2.4.4/gems/scoped_search-4.1.4/lib/scoped_search/definition.rb:123:in `type'
12:10:12 rails.1   |  | /home/vagrant/.rvm/gems/ruby-2.4.4/gems/scoped_search-4.1.4/lib/scoped_search/definition.rb:144:in `numerical?'                                                                                                                                                  
12:10:12 rails.1   |  | /home/vagrant/.rvm/gems/ruby-2.4.4/gems/scoped_search-4.1.4/lib/scoped_search/definition.rb:236:in `operator_by_field_name'                                                                                                                                      
12:10:12 rails.1   |  | /home/vagrant/.rvm/gems/ruby-2.4.4/gems/scoped_search-4.1.4/lib/scoped_search/auto_complete_builder.rb:273:in `complete_operator'                                                                                                                                
12:10:12 rails.1   |  | /home/vagrant/.rvm/gems/ruby-2.4.4/gems/scoped_search-4.1.4/lib/scoped_search/auto_complete_builder.rb:47:in `build_autocomplete_options'
12:10:12 rails.1   |  | /home/vagrant/.rvm/gems/ruby-2.4.4/gems/scoped_search-4.1.4/lib/scoped_search/auto_complete_builder.rb:21:in `auto_complete'
12:10:12 rails.1   |  | /home/vagrant/.rvm/gems/ruby-2.4.4/gems/scoped_search-4.1.4/lib/scoped_search/definition.rb:319:in `complete_for'
12:10:12 rails.1   |  | /home/vagrant/.rvm/gems/ruby-2.4.4/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:66:in `block in complete_for'
12:10:12 rails.1   |  | /home/vagrant/.rvm/gems/ruby-2.4.4/gems/activerecord-5.1.6/lib/active_record/relation.rb:336:in `scoping'
12:10:12 rails.1   |  | /home/vagrant/.rvm/gems/ruby-2.4.4/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:66:in `complete_for'
12:10:12 rails.1   |  | /home/vagrant/katello/app/controllers/katello/concerns/filtered_auto_complete_search.rb:11:in `auto_complete_search'
```

It is pretty easy to repro in Katello nightly, if you need instructions on how to repro just let me know.

**Comment by PaulSD** [comment]
#182 fixes this for me, both with and without `:only_explicit => true` on the `evr` field in Katello.

**Comment by PaulSD** [comment]
@ares Any chance you could merge and re-release?

**Comment by ares** [comment]
PR merged, this will be fixed in 4.1.5
